"""Outreach content generation — turns a scraped job + audience into a recruiter
email or LinkedIn message via the LLM, with a deterministic template fallback.

Used by app/routes/outreach_routes.py. Generation goes through
LLMService.generate_text, so it uses the SAME centrally configured provider as
job harvesting (EXTRACTION_LLM_MODEL: local LLM / OpenRouter / Claude) and the
resolved provider/model + token usage are captured for the llm_calls audit row.
Any LLM failure (provider down, timeout, unparseable JSON) degrades to the static
reference template rendered with the company name — the send flow still works.
"""
from __future__ import annotations

import json
import re
import time
from dataclasses import dataclass

import structlog

from app.prompts import outreach_prompts
from app.services.llm_service import LLMService

logger = structlog.get_logger(__name__)


@dataclass
class GenMeta:
    """LLM-call metadata captured per generation, written to the llm_calls row."""
    provider: str = "claude"
    model: str = ""
    prompt: str = ""
    response: str = ""
    input_tokens: int | None = None
    output_tokens: int | None = None
    latency_ms: int | None = None
    success: bool = True
    error_message: str | None = None


@dataclass
class EmailDraft:
    subject: str
    body: str
    fallback_used: bool
    meta: GenMeta


@dataclass
class LinkedinDraft:
    message: str
    fallback_used: bool
    meta: GenMeta


def _strip_fences(text: str) -> str:
    """Drop a leading ```/```json fence and trailing ``` if the model added them."""
    t = (text or "").strip()
    t = re.sub(r"^```(?:json)?\s*", "", t)
    t = re.sub(r"\s*```$", "", t)
    return t.strip()


class OutreachService:
    def __init__(self, llm_service: LLMService) -> None:
        self._llm = llm_service

    async def _complete(self, prompt: str, system: str, *, json_mode: bool) -> tuple[str, GenMeta]:
        """Generate via the centrally configured provider (EXTRACTION_LLM_MODEL) —
        local LLM / OpenRouter / Claude, same as harvesting. json_mode=True asks
        the provider for a JSON object (the email {subject, body}); False yields
        plain text (the LinkedIn message)."""
        provider, model = self._llm.resolve_target()
        meta = GenMeta(provider=provider, model=model, prompt=prompt)
        t0 = time.monotonic()
        try:
            text, input_tokens, output_tokens, provider, model = await self._llm.generate_text(
                prompt, system, json_mode=json_mode
            )
            meta.provider = provider
            meta.model = model
            meta.latency_ms = int((time.monotonic() - t0) * 1000)
            meta.input_tokens = input_tokens
            meta.output_tokens = output_tokens
            meta.response = text
            return text, meta
        except Exception as exc:
            meta.latency_ms = int((time.monotonic() - t0) * 1000)
            meta.success = False
            meta.error_message = str(exc)
            logger.warning("outreach_llm_failed", provider=provider, model=model, error=str(exc))
            return "", meta

    # ── Email ────────────────────────────────────────────────────────────────

    async def generate_email(
        self, job: dict, client_type: str, tone: str, regenerate: bool = False,
        sender_email: str = "", deck_url: str = "",
    ) -> EmailDraft:
        """`sender_email` is the address the recipient is invited to reply to
        (the logged-in user). It's appended — as a reach-out line above the
        sign-off — to whatever pitch the LLM (or the fallback template) produces,
        never generated by the LLM itself, so the contact detail is always right.
        `deck_url`, when set, adds a clickable link to the hosted company-overview
        deck (in place of the old file attachment); when empty, no deck line."""
        company = (job.get("company") or "").strip()
        prompt = outreach_prompts.build_email_prompt(client_type, tone, job, sender_email)
        if regenerate:
            prompt += "\n\nProduce a distinctly different variation from any previous version."

        text, meta = await self._complete(prompt, outreach_prompts.EMAIL_SYSTEM_PROMPT, json_mode=True)
        if meta.success and text:
            parsed = self._parse_email_json(text)
            if parsed:
                subject, pitch = parsed
                body = outreach_prompts.append_closing(pitch, sender_email, deck_url)
                return EmailDraft(subject=subject, body=body, fallback_used=False, meta=meta)
            # Model responded but not with usable JSON — mark the audit row and fall back.
            meta.success = False
            meta.error_message = meta.error_message or "unparseable LLM JSON"

        subject, body = outreach_prompts.render_email_fallback(client_type, company, sender_email, deck_url)
        return EmailDraft(subject=subject, body=body, fallback_used=True, meta=meta)

    @staticmethod
    def _parse_email_json(text: str) -> tuple[str, str] | None:
        try:
            data = json.loads(_strip_fences(text))
        except Exception:
            return None
        if not isinstance(data, dict):
            return None
        subject = str(data.get("subject", "")).strip()
        body = str(data.get("body", "")).strip()
        return (subject, body) if subject and body else None

    # ── LinkedIn ───────────────────────────────────────────────────────────────

    async def generate_linkedin(self, job: dict, regenerate: bool = False) -> LinkedinDraft:
        company = (job.get("company") or "").strip()
        prompt = outreach_prompts.build_linkedin_prompt(job)
        if regenerate:
            prompt += "\n\nProduce a distinctly different variation from any previous version."

        text, meta = await self._complete(prompt, outreach_prompts.LINKEDIN_SYSTEM_PROMPT, json_mode=False)
        message = _strip_fences(text)
        if meta.success and message:
            return LinkedinDraft(message=message, fallback_used=False, meta=meta)
        if meta.success and not message:
            meta.success = False
            meta.error_message = meta.error_message or "empty LLM response"
        return LinkedinDraft(
            message=outreach_prompts.render_linkedin_fallback(company),
            fallback_used=True,
            meta=meta,
        )
